"""Convert benchmark .bat files into self-contained .clp files."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from ferric_tools._manifest import utc_now_iso
from ferric_tools._paths import repo_root

app = typer.Typer(help="Convert benchmark .bat files into self-contained .clp files.")
console = Console(stderr=True)

BENCHMARK_DIRS = [
    ("clips-official/examples/manners", "clips-official"),
    ("clips-official/examples/waltz", "clips-official"),
    ("clips-official/examples/sudoku", "clips-official"),
]

IGNORED_COMMANDS = {"clear", "unwatch", "watch", "set-strategy", "reset", "run"}


def parse_bat_file(bat_path: Path) -> dict:
    """Parse a .bat file and extract load/load-facts commands plus any extras."""
    loads: list[str] = []
    load_facts: list[str] = []
    extras: list[str] = []

    text = bat_path.read_text(encoding="utf-8", errors="replace")

    for m in re.finditer(r"\(([^()]*(?:\([^()]*\))*[^()]*)\)", text):
        body = m.group(1).strip()
        if not body:
            continue

        parts = body.split(None, 1)
        cmd = parts[0].lower()
        arg = parts[1].strip() if len(parts) > 1 else ""

        if cmd in IGNORED_COMMANDS:
            continue
        elif cmd == "load":
            filename = arg.strip('"').strip("'").replace("//", "/")
            loads.append(filename)
        elif cmd == "load-facts":
            filename = arg.strip('"').strip("'").replace("//", "/")
            load_facts.append(filename)
        else:
            extras.append(m.group(0))

    return {"loads": loads, "load_facts": load_facts, "extras": extras}


def build_combined_clp(
    bat_path: Path, parsed: dict, bat_dir: Path, root: Path
) -> tuple[str | None, list[str]]:
    """Build the text of a self-contained .clp file from parsed bat data."""
    warnings: list[str] = []
    sections: list[str] = []

    rel = bat_path.relative_to(root) if bat_path.is_relative_to(root) else bat_path
    sections.append(
        f";;; =================================================================\n"
        f";;; Auto-generated self-contained benchmark from {rel}\n"
        f";;; Generated by ferric-bat-convert\n"
        f";;; =================================================================\n"
    )

    for filename in parsed["loads"]:
        file_path = (bat_dir / filename).resolve()
        if not file_path.exists():
            warnings.append(f"Referenced file not found: {filename} (from {bat_path.name})")
            return None, warnings
        content = file_path.read_text(encoding="utf-8", errors="replace")
        sections.append(f"\n;;; --- Inlined from {filename} ---\n\n{content.rstrip()}\n")

    fact_count = len(parsed["load_facts"])
    for i, filename in enumerate(parsed["load_facts"]):
        file_path = (bat_dir / filename).resolve()
        if not file_path.exists():
            warnings.append(f"Referenced file not found: {filename} (from {bat_path.name})")
            return None, warnings
        content = file_path.read_text(encoding="utf-8", errors="replace")

        deffacts_name = "loaded-data" if fact_count == 1 else f"loaded-data-{i + 1}"
        indented = "\n".join(
            f"  {line}" if line.strip() else "" for line in content.rstrip().split("\n")
        )
        sections.append(
            f"\n;;; --- Facts from {filename} ---\n\n(deffacts {deffacts_name}\n{indented}\n)\n"
        )

    if parsed["extras"]:
        sections.append("\n;;; --- Additional commands from batch file ---\n")
        for extra in parsed["extras"]:
            sections.append("\n;;; NOTE: The following command was in the .bat file.\n")
            sections.append(";;; It may need manual review.\n")
            sections.append(f";;; {extra}\n")

    return "\n".join(sections), warnings


def update_manifest(manifest_path: Path, updates: list[dict], dry_run: bool = False) -> None:
    """Apply updates to the manifest."""
    if not manifest_path.exists():
        print(f"  WARNING: Manifest not found at {manifest_path}, skipping update")
        return

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    files = manifest.get("files", {})
    changed = False

    for upd in updates:
        key = upd["key"]
        if key not in files:
            print(f"  WARNING: Manifest key not found: {key}")
            continue
        entry = files[key]
        entry["generated"] = upd["generated"]
        entry["classification"] = "pending"
        entry["reason"] = "benchmark-converted"
        changed = True

    if changed:
        summary = {"total": 0, "equivalent": 0, "divergent": 0, "incompatible": 0, "pending": 0}
        for entry in files.values():
            summary["total"] += 1
            cls = entry.get("classification", "pending")
            if cls in summary:
                summary[cls] += 1
        manifest["summary"] = summary
        manifest["generated"] = utc_now_iso()

        if dry_run:
            print(f"  Would update manifest with {len(updates)} entries")
        else:
            manifest_path.write_text(
                json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            print(f"  Updated manifest ({len(updates)} entries)")


@app.command()
def main(
    examples_dir: Annotated[
        Path | None,
        typer.Option(help="Base directory for source files"),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option(help="Where to write generated .clp files"),
    ] = None,
    manifest_opt: Annotated[
        Path | None,
        typer.Option("--manifest", help="Path to compat-manifest.json"),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option(help="Show what would be done without writing files"),
    ] = False,
) -> None:
    """Convert benchmark .bat files into self-contained .clp files."""
    root = repo_root()
    ed = (Path(examples_dir) if examples_dir else root / "tests" / "examples").resolve()
    od = (Path(output_dir) if output_dir else root / "tests" / "generated" / "benchmarks").resolve()
    mp = (Path(manifest_opt) if manifest_opt else ed / "compat-manifest.json").resolve()

    print(f"Examples dir:  {ed}")
    print(f"Output dir:    {od}")
    print(f"Manifest:      {mp}")
    print(f"Dry run:       {dry_run}")
    print()

    manifest_updates: list[dict] = []
    generated_count = 0
    skipped_count = 0
    warning_count = 0

    for bench_rel, source_label in BENCHMARK_DIRS:
        bench_dir = ed / bench_rel
        if not bench_dir.is_dir():
            print(f"  WARNING: Benchmark directory not found: {bench_dir}")
            warning_count += 1
            continue

        bat_files = sorted(bench_dir.glob("*.bat"))
        if not bat_files:
            print(f"  No .bat files in {bench_dir}")
            continue

        for bat_path in bat_files:
            bat_stem = bat_path.stem
            print(f"Processing: {bat_path.relative_to(ed)}")

            parsed = parse_bat_file(bat_path)
            if not parsed["loads"] and not parsed["load_facts"]:
                print("  SKIP: No load or load-facts commands found")
                skipped_count += 1
                continue

            clp_text, warnings = build_combined_clp(bat_path, parsed, bench_dir, root)

            for w in warnings:
                print(f"  WARNING: {w}")
                warning_count += 1

            if clp_text is None:
                print("  SKIP: Missing referenced file(s)")
                skipped_count += 1
                continue

            dest_dir = od / source_label
            dest_path = dest_dir / f"{bat_stem}.clp"

            if dry_run:
                print(f"  Would write: {dest_path.relative_to(root)}")
                lines = clp_text.count("\n")
                print(
                    f"  ({lines} lines, {len(parsed['loads'])} load(s), "
                    f"{len(parsed['load_facts'])} load-facts, "
                    f"{len(parsed['extras'])} extra(s))"
                )
            else:
                dest_dir.mkdir(parents=True, exist_ok=True)
                dest_path.write_text(clp_text, encoding="utf-8")
                print(f"  Wrote: {dest_path.relative_to(root)}")

            generated_count += 1

            manifest_key = str(bat_path.relative_to(ed))
            generated_rel = str(dest_path.relative_to(root))
            manifest_updates.append({"key": manifest_key, "generated": generated_rel})

    print()
    if manifest_updates:
        update_manifest(mp, manifest_updates, dry_run=dry_run)

    print()
    print("Summary:")
    print(f"  Generated:  {generated_count}")
    print(f"  Skipped:    {skipped_count}")
    print(f"  Warnings:   {warning_count}")

    if warning_count > 0:
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
