/*
 * ferric.h - C API for the Ferric rules engine
 *
 * ============================================================
 * THREAD SAFETY
 * ============================================================
 *
 * Engine handles (FerricEngine*) are bound to the thread that
 * created them. Every ferric_engine_* function validates thread
 * affinity before any state mutation.
 *
 * - Creating thread: all operations succeed normally.
 * - Other threads: operations return FERRIC_ERROR_THREAD_VIOLATION
 *   with a descriptive message in the global error channel.
 * - Exception: ferric_engine_last_error() and
 *   ferric_engine_last_error_copy() skip thread checks
 *   (diagnostic access should always work).
 *
 * The global error functions (ferric_last_error_global, etc.)
 * use thread-local storage and are safe to call from any thread.
 *
 * ============================================================
 * OWNERSHIP AND LIFETIME
 * ============================================================
 *
 * 1. Engine handles: Caller owns the handle returned by
 *    ferric_engine_new(). Must free with ferric_engine_free().
 *
 * 2. Borrowed string pointers: Pointers returned by
 *    ferric_last_error_global() and ferric_engine_last_error()
 *    are valid until the next FFI call that may modify that
 *    error channel. Do NOT free these pointers.
 *
 * 3. Owned string pointers: String fields in FerricValue
 *    (string_ptr for Symbol/String types) are heap-allocated.
 *    Free with ferric_string_free() or ferric_value_free().
 *
 * 4. FerricValue ownership: Values returned through out-params
 *    (e.g., ferric_engine_get_fact_field) are caller-owned.
 *    Free with ferric_value_free() which recursively releases
 *    owned strings and multifield arrays.
 *
 * 5. Multifield arrays: FerricValue.multifield_ptr is a heap-
 *    allocated array. Free with ferric_value_array_free() or
 *    ferric_value_free() (which handles it recursively).
 *
 * 6. External address pointers: FerricValue.external_pointer
 *    is NOT owned by the FFI. Lifetime is caller-managed.
 *
 * 7. Output string pointers: ferric_engine_get_output() returns
 *    a borrowed pointer valid until the next call that writes
 *    to that channel. Do NOT free.
 *
 * 8. Bounds annotations: Pointer parameters and struct fields
 *    carry FERRIC_COUNTED_BY, FERRIC_SIZED_BY, and
 *    FERRIC_NULL_TERMINATED annotations when compiled with
 *    Clang -fbounds-safety. Define FERRIC_NO_BOUNDS_ANNOTATIONS
 *    before including this header to suppress.
 */

#ifndef FERRIC_H
#define FERRIC_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/*
 * ============================================================
 * BOUNDS-SAFETY ANNOTATIONS
 * ============================================================
 *
 * When compiled with a supporting compiler (Clang with
 * -fbounds-safety), pointer parameters, struct fields, and
 * return types carry bounds annotations that enable static
 * and runtime checking.
 *
 * To disable all annotations, define FERRIC_NO_BOUNDS_ANNOTATIONS
 * before including this header.
 */

#ifndef FERRIC_NO_BOUNDS_ANNOTATIONS
  #if defined(__clang__) && defined(__has_feature)
    #if __has_feature(bounds_safety)
      #define FERRIC_COUNTED_BY(N) __counted_by(N)
      #define FERRIC_SIZED_BY(N) __sized_by(N)
      #define FERRIC_NULL_TERMINATED __null_terminated
    #endif
  #endif
  #ifndef FERRIC_COUNTED_BY
    #define FERRIC_COUNTED_BY(N)
    #define FERRIC_SIZED_BY(N)
    #define FERRIC_NULL_TERMINATED
  #endif
#else
  #define FERRIC_COUNTED_BY(N)
  #define FERRIC_SIZED_BY(N)
  #define FERRIC_NULL_TERMINATED
#endif


// C-facing error codes returned by all fallible FFI entry points.
//
// Stable numeric values — new codes may be added but existing values
// must never change.
typedef enum FerricError {
    // Operation succeeded.
    FERRIC_ERROR_OK = 0,
    // A required pointer argument was null.
    FERRIC_ERROR_NULL_POINTER = 1,
    // Engine called from wrong thread.
    FERRIC_ERROR_THREAD_VIOLATION = 2,
    // Requested fact/item not found.
    FERRIC_ERROR_NOT_FOUND = 3,
    // Parse error in CLIPS source.
    FERRIC_ERROR_PARSE_ERROR = 4,
    // Compilation/validation error.
    FERRIC_ERROR_COMPILE_ERROR = 5,
    // Runtime evaluation error.
    FERRIC_ERROR_RUNTIME_ERROR = 6,
    // I/O error (file not found, etc).
    FERRIC_ERROR_IO_ERROR = 7,
    // Provided buffer too small for result.
    FERRIC_ERROR_BUFFER_TOO_SMALL = 8,
    // Invalid argument value.
    FERRIC_ERROR_INVALID_ARGUMENT = 9,
    // Serialization or deserialization error.
    FERRIC_ERROR_SERIALIZATION_ERROR = 10,
    // Internal/unexpected error.
    FERRIC_ERROR_INTERNAL_ERROR = 99,
} FerricError;

// C-facing value type discriminant.
typedef enum FerricValueType {
    FERRIC_VALUE_TYPE_VOID = 0,
    FERRIC_VALUE_TYPE_INTEGER = 1,
    FERRIC_VALUE_TYPE_FLOAT = 2,
    FERRIC_VALUE_TYPE_SYMBOL = 3,
    FERRIC_VALUE_TYPE_STRING = 4,
    FERRIC_VALUE_TYPE_MULTIFIELD = 5,
    FERRIC_VALUE_TYPE_EXTERNAL_ADDRESS = 6,
} FerricValueType;

// C-facing fact type discriminant.
typedef enum FerricFactType {
    FERRIC_FACT_TYPE_ORDERED = 0,
    FERRIC_FACT_TYPE_TEMPLATE = 1,
} FerricFactType;

// C-facing halt reason returned by `ferric_engine_run_ex`.
typedef enum FerricHaltReason {
    FERRIC_HALT_REASON_AGENDA_EMPTY = 0,
    FERRIC_HALT_REASON_LIMIT_REACHED = 1,
    FERRIC_HALT_REASON_HALT_REQUESTED = 2,
} FerricHaltReason;

#if defined(FERRIC_SERDE)
// Serialization format selector for `ferric_engine_serialize_as` and
// `ferric_engine_deserialize_as`.
typedef enum FerricSerializationFormat {
    // Compact binary (bincode). Fast and small.
    FERRIC_SERIALIZATION_FORMAT_BINCODE = 0,
    // JSON (human-readable, larger output).
    FERRIC_SERIALIZATION_FORMAT_JSON = 1,
    // CBOR (Concise Binary Object Representation).
    FERRIC_SERIALIZATION_FORMAT_CBOR = 2,
    // `MessagePack` (compact binary, JSON-like schema).
    FERRIC_SERIALIZATION_FORMAT_MESSAGE_PACK = 3,
    // Postcard (compact, `no_std`-friendly binary).
    FERRIC_SERIALIZATION_FORMAT_POSTCARD = 4,
} FerricSerializationFormat;
#endif

// C-facing string-encoding configuration for `FerricConfig`.
typedef enum FerricStringEncoding {
    FERRIC_STRING_ENCODING_ASCII = 0,
    FERRIC_STRING_ENCODING_UTF8 = 1,
    FERRIC_STRING_ENCODING_ASCII_SYMBOLS_UTF8_STRINGS = 2,
} FerricStringEncoding;

// C-facing conflict-resolution strategy for `FerricConfig`.
typedef enum FerricConflictStrategy {
    FERRIC_CONFLICT_STRATEGY_DEPTH = 0,
    FERRIC_CONFLICT_STRATEGY_BREADTH = 1,
    FERRIC_CONFLICT_STRATEGY_LEX = 2,
    FERRIC_CONFLICT_STRATEGY_MEA = 3,
} FerricConflictStrategy;

// Opaque engine handle exposed to C.
//
// Contains the Rust [`Engine`] plus per-engine error state.
// C code receives `*mut FerricEngine` as an opaque pointer.
typedef struct FerricEngine FerricEngine;

// C-facing engine configuration used by `ferric_engine_new_with_config`.
typedef struct FerricConfig {
    // Raw `FerricStringEncoding` discriminant.
    uint32_t string_encoding;
    // Raw `FerricConflictStrategy` discriminant.
    uint32_t strategy;
    uintptr_t max_call_depth;
} FerricConfig;

// C-facing value representation.
//
// ## Ownership
//
// - `string_ptr`: when non-null, is a heap-allocated NUL-terminated string.
//   The caller must free it with `ferric_string_free` or `ferric_value_free`.
// - `multifield_ptr`: when non-null, is a heap-allocated array of `FerricValue`s.
//   The caller must free it with `ferric_value_free` (which recursively frees elements)
//   or `ferric_value_array_free`.
// - `external_pointer`: NOT owned by `FerricValue`. Lifetime is caller-managed.
//
// ## Active Fields by Type
//
// | `value_type` | Active fields |
// |---|---|
// | Void | (none) |
// | Integer | `integer` |
// | Float | `float` |
// | Symbol | `string_ptr` (owned) |
// | String | `string_ptr` (owned) |
// | Multifield | `multifield_ptr` (owned), `multifield_len` |
// | ExternalAddress | `external_type_id`, `external_pointer` |
typedef struct FerricValue {
    enum FerricValueType value_type;
    int64_t integer;
    double float_;
    char * FERRIC_NULL_TERMINATED string_ptr;
    struct FerricValue *multifield_ptr FERRIC_COUNTED_BY(multifield_len);
    uintptr_t multifield_len;
    uint32_t external_type_id;
    void *external_pointer;
} FerricValue;

#if defined(FERRIC_SERDE)
// Callback type for caller-controlled memory allocation.
//
// When non-null, called by serialization functions with the exact byte
// count needed. The `context` parameter is passed through unchanged from
// the serialize call.
//
// Must return a pointer to at least `size` writable bytes, or null to
// signal allocation failure.
typedef uint8_t *(*FerricAllocFn)(uintptr_t size, void *context);
#endif

// Create a new engine with default configuration.
//
// Returns a heap-allocated engine handle, or null on failure.
// The caller owns the returned handle and must free it with
// `ferric_engine_free`.
//
// # Safety
//
// The returned pointer must be freed with `ferric_engine_free`.
// The engine is bound to the creating thread.
struct FerricEngine *ferric_engine_new(void);

// Create a new engine with optional caller-provided configuration.
//
// If `config` is null, defaults are used.
//
// # Safety
//
// - `config` may be null.
// - Returned pointer must be freed with `ferric_engine_free`.
struct FerricEngine *ferric_engine_new_with_config(const struct FerricConfig *config);

// Free an engine handle.
//
// Null pointers are safely ignored. After this call, the pointer
// is invalid and must not be used.
//
// # Safety
//
// - `engine` must be a pointer returned by `ferric_engine_new` or null.
// - The engine must not be in use by another call when freed.
// - The engine must be freed from the same thread that created it.
enum FerricError ferric_engine_free(struct FerricEngine *engine);

// Load a CLIPS source string into the engine.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `source` must be a valid NUL-terminated UTF-8 string.
enum FerricError ferric_engine_load_string(struct FerricEngine *engine, const char * FERRIC_NULL_TERMINATED source);

// Retrieve the last per-engine error message.
//
// Returns a pointer to a NUL-terminated string, or null if no error
// is stored. The pointer is valid until the next call on this engine.
//
// # Safety
//
// - `engine` must be a valid engine pointer or null.
const char * FERRIC_NULL_TERMINATED ferric_engine_last_error(const struct FerricEngine *engine);

// Copy the per-engine error message into a caller-provided buffer.
//
// Same contract as `ferric_last_error_global_copy` but reads from the
// per-engine error channel. Deliberately skips thread-affinity check
// (diagnostic operation).
//
// ## Contract
//
// | Condition | Return | `*out_len` |
// |-----------|--------|------------|
// | `engine` is null | `NullPointer` | 0 |
// | No error stored | `NotFound` | 0 |
// | `out_len` is null | `InvalidArgument` | (not written) |
// | `buf` is null AND `buf_len` is 0 (size query) | `Ok` | required size (incl. NUL) |
// | `buf` non-null, `buf_len` >= needed | `Ok` | bytes written (incl. NUL) |
// | `buf` non-null, `buf_len` < needed | `BufferTooSmall` | full needed size (incl. NUL) |
//
// # Safety
//
// - `engine` must be a valid engine pointer or null (null → `NullPointer`).
// - `buf` must point to `buf_len` writable bytes, or be null for size query.
// - `out_len` must be a valid pointer (non-null).
enum FerricError ferric_engine_last_error_copy(const struct FerricEngine *engine,
                                               char *buf FERRIC_SIZED_BY(buf_len),
                                               uintptr_t buf_len,
                                               uintptr_t *out_len);

// Clear the per-engine error state.
//
// # Safety
//
// - `engine` must be a valid engine pointer or null (null returns `NullPointer`).
enum FerricError ferric_engine_clear_error(struct FerricEngine *engine);

// Reset the engine to its initial state.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
enum FerricError ferric_engine_reset(struct FerricEngine *engine);

// Run the engine, executing rules until the agenda is empty, the limit is
// reached, or a halt action fires.
//
// - `limit`: Maximum rule firings. Pass `-1` for unlimited.
// - `out_fired`: If non-null, receives the number of rules fired.
//
// Returns `FerricError::Ok` on success.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_fired` may be null (output is simply not written).
enum FerricError ferric_engine_run(struct FerricEngine *engine, int64_t limit, uint64_t *out_fired);

// Execute a single rule firing step.
//
// - `out_status`: If non-null, receives: `1` = rule fired, `0` = agenda empty,
//   `-1` = halted.
//
// Returns `FerricError::Ok` on success.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_status` may be null.
enum FerricError ferric_engine_step(struct FerricEngine *engine, int32_t *out_status);

// Assert a fact from a CLIPS source string (e.g., `"(assert (color red))"`).
//
// The source is parsed as a top-level CLIPS form and evaluated. If
// `out_fact_id` is non-null and an assert occurred, it receives the first
// asserted fact's opaque ID. If no fact was asserted, `0` is written.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `source` must be a valid NUL-terminated UTF-8 string.
// - `out_fact_id` may be null.
enum FerricError ferric_engine_assert_string(struct FerricEngine *engine,
                                             const char * FERRIC_NULL_TERMINATED source,
                                             uint64_t *out_fact_id);

// Retract a fact by its opaque fact ID obtained from a previous assert.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `fact_id` must be a valid fact ID obtained from a previous assert.
enum FerricError ferric_engine_retract(struct FerricEngine *engine, uint64_t fact_id);

// Get the engine's captured output for a named channel (e.g., `"stdout"`).
//
// Returns a pointer to a NUL-terminated string, or null if the channel has
// no output, the engine pointer is null, or the channel pointer is null.
// The returned pointer is valid until the next call that writes to that channel.
//
// # Safety
//
// - `engine` must be a valid engine pointer or null.
// - `channel` must be a valid NUL-terminated UTF-8 string or null.
const char * FERRIC_NULL_TERMINATED ferric_engine_get_output(const struct FerricEngine *engine, const char * FERRIC_NULL_TERMINATED channel);

// Get the number of action diagnostics captured during recent execution.
//
// Diagnostics are collected by `run`/`step` when non-fatal action errors occur
// (for example module visibility failures surfaced as warnings).
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_action_diagnostic_count(const struct FerricEngine *engine,
                                                       uintptr_t *out_count);

// Copy one action diagnostic message into a caller-provided buffer.
//
// Message selection is by zero-based index into the current action-diagnostic list.
// The copy contract matches `ferric_last_error_global_copy`.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `buf` must point to `buf_len` writable bytes, or be null for size query.
// - `out_len` must be a valid pointer (non-null).
enum FerricError ferric_engine_action_diagnostic_copy(const struct FerricEngine *engine,
                                                      uintptr_t index,
                                                      char *buf FERRIC_SIZED_BY(buf_len),
                                                      uintptr_t buf_len,
                                                      uintptr_t *out_len);

// Clear all stored action diagnostics.
//
// # Safety
//
// - `engine` must be a valid engine pointer or null (null returns `NullPointer`).
enum FerricError ferric_engine_clear_action_diagnostics(struct FerricEngine *engine);

// Get the count of user-visible facts in working memory.
//
// The synthetic `(initial-fact)` is excluded from the count.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_fact_count(const struct FerricEngine *engine, uintptr_t *out_count);

// Get the number of fields in a fact.
//
// For ordered facts, returns the number of field values.
// For template facts, returns the number of slots.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_get_fact_field_count(const struct FerricEngine *engine,
                                                    uint64_t fact_id,
                                                    uintptr_t *out_count);

// Get a single field from a fact as a `FerricValue`.
//
// For ordered facts, `index` is the field position (0-based).
// For template facts, `index` is the slot position (0-based).
//
// The returned `FerricValue` is written to `*out_value`. The caller owns
// any heap-allocated resources (`string_ptr`, `multifield_ptr`) and must free
// them with `ferric_value_free` or the type-specific free functions.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_value` must be a valid pointer to a `FerricValue`.
enum FerricError ferric_engine_get_fact_field(const struct FerricEngine *engine,
                                              uint64_t fact_id,
                                              uintptr_t index,
                                              struct FerricValue *out_value);

// Get a global variable's value.
//
// The name should NOT include the `?*` prefix/suffix — pass just the base name
// (e.g., `"x"` for `?*x*`).
//
// Module/global visibility resolution follows the runtime's standard rules.
// Ambiguity and not-found conditions produce runtime-authored diagnostics.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `name` must be a valid NUL-terminated UTF-8 string.
// - `out_value` must be a valid pointer to a `FerricValue`.
enum FerricError ferric_engine_get_global(const struct FerricEngine *engine,
                                          const char * FERRIC_NULL_TERMINATED name,
                                          struct FerricValue *out_value);

// Copy all user-visible fact IDs to a caller-provided array.
//
// - Size query: `out_ids == NULL && max_ids == 0` → `*out_count` receives total count.
// - Partial copy: copies up to `max_ids` IDs, `*out_count` always receives total count.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
// - If `out_ids` is non-null, it must point to space for at least `max_ids` `u64`s.
enum FerricError ferric_engine_fact_ids(const struct FerricEngine *engine,
                                        uint64_t *out_ids FERRIC_COUNTED_BY(max_ids),
                                        uintptr_t max_ids,
                                        uintptr_t *out_count);

// Find fact IDs by relation name.
//
// Same size-query pattern as `ferric_engine_fact_ids`.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `relation` must be a valid NUL-terminated string.
// - `out_count` must be a valid pointer.
// - If `out_ids` is non-null, it must point to space for at least `max_ids` `u64`s.
enum FerricError ferric_engine_find_fact_ids(const struct FerricEngine *engine,
                                             const char * FERRIC_NULL_TERMINATED relation,
                                             uint64_t *out_ids FERRIC_COUNTED_BY(max_ids),
                                             uintptr_t max_ids,
                                             uintptr_t *out_count);

// Discriminate ordered vs. template fact.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_type` must be a valid pointer.
enum FerricError ferric_engine_get_fact_type(const struct FerricEngine *engine,
                                             uint64_t fact_id,
                                             enum FerricFactType *out_type);

// Get the relation name for an ordered fact.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_get_fact_relation(const struct FerricEngine *engine,
                                                 uint64_t fact_id,
                                                 char *buf FERRIC_SIZED_BY(buf_len),
                                                 uintptr_t buf_len,
                                                 uintptr_t *out_len);

// Get the template name for a template fact.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_get_fact_template_name(const struct FerricEngine *engine,
                                                      uint64_t fact_id,
                                                      char *buf FERRIC_SIZED_BY(buf_len),
                                                      uintptr_t buf_len,
                                                      uintptr_t *out_len);

// Assert an ordered fact from structured values, bypassing CLIPS source parsing.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `relation` must be a valid NUL-terminated string.
// - If `fields` is non-null, it must point to `field_count` valid `FerricValue`s.
// - `out_fact_id` may be null.
enum FerricError ferric_engine_assert_ordered(struct FerricEngine *engine,
                                              const char * FERRIC_NULL_TERMINATED relation,
                                              const struct FerricValue *fields FERRIC_COUNTED_BY(field_count),
                                              uintptr_t field_count,
                                              uint64_t *out_fact_id);

// Get the number of registered templates.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_template_count(const struct FerricEngine *engine,
                                              uintptr_t *out_count);

// Get the name of a template by zero-based index.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_template_name(const struct FerricEngine *engine,
                                             uintptr_t index,
                                             char *buf FERRIC_SIZED_BY(buf_len),
                                             uintptr_t buf_len,
                                             uintptr_t *out_len);

// Get the number of slots in a named template.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `template_name` must be a valid NUL-terminated string.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_template_slot_count(const struct FerricEngine *engine,
                                                   const char * FERRIC_NULL_TERMINATED template_name,
                                                   uintptr_t *out_count);

// Get the name of a slot in a named template by zero-based index.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `template_name` must be a valid NUL-terminated string.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_template_slot_name(const struct FerricEngine *engine,
                                                  const char * FERRIC_NULL_TERMINATED template_name,
                                                  uintptr_t slot_index,
                                                  char *buf FERRIC_SIZED_BY(buf_len),
                                                  uintptr_t buf_len,
                                                  uintptr_t *out_len);

// Get the number of registered rules.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_rule_count(const struct FerricEngine *engine, uintptr_t *out_count);

// Get the name and salience of a rule by zero-based index.
//
// The rule name is written to `buf` using the standard buffer copy pattern.
// Salience is written to `*out_salience` if non-null.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
// - `out_salience` may be null.
enum FerricError ferric_engine_rule_info(const struct FerricEngine *engine,
                                         uintptr_t index,
                                         char *buf FERRIC_SIZED_BY(buf_len),
                                         uintptr_t buf_len,
                                         uintptr_t *out_len,
                                         int32_t *out_salience);

// Get the current module name.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_current_module(const struct FerricEngine *engine,
                                              char *buf FERRIC_SIZED_BY(buf_len),
                                              uintptr_t buf_len,
                                              uintptr_t *out_len);

// Get the name of the module at the top of the focus stack.
//
// Standard buffer copy pattern. Returns `NotFound` if the focus stack is empty.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_get_focus(const struct FerricEngine *engine,
                                         char *buf FERRIC_SIZED_BY(buf_len),
                                         uintptr_t buf_len,
                                         uintptr_t *out_len);

// Get the depth of the focus stack.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_depth` must be a valid pointer.
enum FerricError ferric_engine_focus_stack_depth(const struct FerricEngine *engine,
                                                 uintptr_t *out_depth);

// Get a focus stack entry by zero-based index.
//
// Index 0 = bottom of stack, last index = top (current focus).
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_focus_stack_entry(const struct FerricEngine *engine,
                                                 uintptr_t index,
                                                 char *buf FERRIC_SIZED_BY(buf_len),
                                                 uintptr_t buf_len,
                                                 uintptr_t *out_len);

// Get the number of registered modules.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_module_count(const struct FerricEngine *engine,
                                            uintptr_t *out_count);

// Get the name of a module by zero-based index.
//
// Standard buffer copy pattern.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_len` must be a valid pointer.
// - If `buf` is non-null, it must point to at least `buf_len` writable bytes.
enum FerricError ferric_engine_module_name(const struct FerricEngine *engine,
                                           uintptr_t index,
                                           char *buf FERRIC_SIZED_BY(buf_len),
                                           uintptr_t buf_len,
                                           uintptr_t *out_len);

// Get the number of activations on the agenda.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_count` must be a valid pointer.
enum FerricError ferric_engine_agenda_count(const struct FerricEngine *engine,
                                            uintptr_t *out_count);

// Check whether the engine is halted.
//
// Writes 1 to `*out_halted` if halted, 0 if not halted.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_halted` must be a valid pointer.
enum FerricError ferric_engine_is_halted(const struct FerricEngine *engine, int32_t *out_halted);

// Request the engine to halt.
//
// Always succeeds. Idempotent — halting an already-halted engine is a no-op.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
enum FerricError ferric_engine_halt(struct FerricEngine *engine);

// Push an input line for the engine's `read`/`readline` functions.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `line` must be a valid NUL-terminated string.
enum FerricError ferric_engine_push_input(struct FerricEngine *engine, const char * FERRIC_NULL_TERMINATED line);

// Reset the engine to a blank slate.
//
// Removes all facts, rules, templates, globals, functions, generics, and
// modules except MAIN. Always succeeds.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
enum FerricError ferric_engine_clear(struct FerricEngine *engine);

// Create an engine from CLIPS source with default configuration.
//
// Returns a heap-allocated engine handle, or null on parse/compile error
// (sets global error message). The engine has already been loaded and reset.
//
// # Safety
//
// - `source` must be a valid NUL-terminated UTF-8 string, or null.
// - Returned pointer must be freed with `ferric_engine_free`.
struct FerricEngine *ferric_engine_new_with_source(const char * FERRIC_NULL_TERMINATED source);

// Create an engine from CLIPS source with explicit configuration.
//
// If `config` is null, defaults are used.
// Returns null on parse/compile error (sets global error message).
//
// # Safety
//
// - `source` must be a valid NUL-terminated UTF-8 string, or null.
// - `config` may be null.
// - Returned pointer must be freed with `ferric_engine_free`.
struct FerricEngine *ferric_engine_new_with_source_config(const char * FERRIC_NULL_TERMINATED source,
                                                          const struct FerricConfig *config);

// Clear a specific output channel.
//
// Always succeeds — clearing a non-existent channel is a no-op.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `channel` must be a valid NUL-terminated string.
enum FerricError ferric_engine_clear_output(struct FerricEngine *engine, const char * FERRIC_NULL_TERMINATED channel);

// Extended run with halt reason output.
//
// Same limit semantics as `ferric_engine_run` (negative = unlimited).
// Additionally writes the halt reason to `*out_reason` if non-null.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_fired` may be null.
// - `out_reason` may be null.
enum FerricError ferric_engine_run_ex(struct FerricEngine *engine,
                                      int64_t limit,
                                      uint64_t *out_fired,
                                      enum FerricHaltReason *out_reason);

// Assert a template fact with named slots.
//
// Looks up the template by name, resolves slot names to positions,
// fills in defaults for unspecified slots, and asserts the fact.
//
// `slot_names` and `slot_values` must each point to `count` elements.
// Each `slot_names[i]` is a NUL-terminated C string naming a slot,
// and `slot_values[i]` is the corresponding value for that slot.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `template_name` must be a valid NUL-terminated string.
// - If `count > 0`, `slot_names` must point to `count` valid NUL-terminated string pointers.
// - If `count > 0`, `slot_values` must point to `count` valid `FerricValue`s.
// - `out_fact_id` may be null.
enum FerricError ferric_engine_assert_template(struct FerricEngine *engine,
                                               const char * FERRIC_NULL_TERMINATED template_name,
                                               const char *const *slot_names FERRIC_COUNTED_BY(count),
                                               const struct FerricValue *slot_values FERRIC_COUNTED_BY(count),
                                               uintptr_t count,
                                               uint64_t *out_fact_id);

// Get a template fact's slot value by name.
//
// The fact must be a template fact. For ordered facts, returns
// `FERRIC_ERROR_INVALID_ARGUMENT`. If the slot name is not found,
// returns `FERRIC_ERROR_NOT_FOUND`.
//
// The returned `FerricValue` is written to `*out_value`. The caller owns
// any heap-allocated resources and must free them with `ferric_value_free`.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `slot_name` must be a valid NUL-terminated string.
// - `out_value` must be a valid pointer to a `FerricValue`.
enum FerricError ferric_engine_get_fact_slot_by_name(const struct FerricEngine *engine,
                                                     uint64_t fact_id,
                                                     const char * FERRIC_NULL_TERMINATED slot_name,
                                                     struct FerricValue *out_value);

// Free an engine handle without checking thread affinity.
//
// This is intended for use by garbage-collected runtimes (Go, etc.) whose
// finalizers run on arbitrary threads. In normal usage, prefer
// `ferric_engine_free` which validates thread affinity.
//
// Null pointers are safely ignored.
//
// # Safety
//
// - `engine` must be a pointer returned by `ferric_engine_new` or null.
// - The engine must not be in use by another call when freed.
// - The caller must guarantee that no other thread is concurrently using this engine.
enum FerricError ferric_engine_free_unchecked(struct FerricEngine *engine);

#if defined(FERRIC_SERDE)
// Serialize engine state to bytes in the specified format.
//
// `format` is a uint32_t corresponding to FerricSerializationFormat discriminants
// (0 = Bincode, 1 = JSON, 2 = CBOR, 3 = MessagePack, 4 = Postcard).
// Returns FERRIC_ERROR_INVALID_ARGUMENT for out-of-range values.
//
// See `ferric_engine_serialize_bincode` for memory allocation details.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_data` and `out_len` must be valid, non-null pointers.
// - If `alloc_fn` is non-null, it must return a valid pointer to `size` bytes
//   (or null to signal failure).
enum FerricError ferric_engine_serialize_as(const struct FerricEngine *engine,
                                            uint32_t format,
                                            FerricAllocFn alloc_fn,
                                            void *alloc_context,
                                            uint8_t **out_data,
                                            uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from bytes in the specified format.
//
// `format` is a uint32_t corresponding to FerricSerializationFormat discriminants
// (0 = Bincode, 1 = JSON, 2 = CBOR, 3 = MessagePack, 4 = Postcard).
// Returns FERRIC_ERROR_INVALID_ARGUMENT for out-of-range values.
//
// See `ferric_engine_deserialize_bincode` for details.
//
// # Safety
//
// - `data` must point to `len` valid, readable bytes.
// - `out_engine` must be a valid, non-null pointer.
// - The returned engine must be freed with `ferric_engine_free`.
enum FerricError ferric_engine_deserialize_as(const uint8_t *data,
                                              uintptr_t len,
                                              uint32_t format,
                                              struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Serialize engine state to bincode.
//
// ## Memory allocation
//
// - If `alloc_fn` is **non-null**: the callback is called once with the exact
//   byte count needed. The serialized data is written into the returned
//   buffer. The caller owns this memory and is responsible for freeing it
//   (via their own allocator). `alloc_context` is passed through unchanged.
//
// - If `alloc_fn` is **null**: Rust allocates the output buffer internally.
//   The caller must free it with `ferric_bytes_free(out_data, out_len)`.
//
// In both cases, `*out_data` and `*out_len` are set on success.
//
// # Safety
//
// - `engine` must be a valid engine pointer.
// - `out_data` and `out_len` must be valid, non-null pointers.
// - If `alloc_fn` is non-null, it must return a valid pointer to `size` bytes
//   (or null to signal failure).
enum FerricError ferric_engine_serialize_bincode(const struct FerricEngine *engine,
                                                 FerricAllocFn alloc_fn,
                                                 void *alloc_context,
                                                 uint8_t **out_data,
                                                 uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from bincode bytes.
//
// The returned engine handle is ready for use (e.g. `ferric_engine_run`).
// Its thread affinity is set to the calling thread.
//
// # Safety
//
// - `data` must point to `len` valid, readable bytes.
// - `out_engine` must be a valid, non-null pointer.
// - The returned engine must be freed with `ferric_engine_free`.
enum FerricError ferric_engine_deserialize_bincode(const uint8_t *data,
                                                   uintptr_t len,
                                                   struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Serialize engine state to JSON.
//
// See `ferric_engine_serialize_bincode` for memory allocation details.
//
// # Safety
//
// Same safety requirements as `ferric_engine_serialize_bincode`.
enum FerricError ferric_engine_serialize_json(const struct FerricEngine *engine,
                                              FerricAllocFn alloc_fn,
                                              void *alloc_context,
                                              uint8_t **out_data,
                                              uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from JSON bytes.
//
// # Safety
//
// Same safety requirements as `ferric_engine_deserialize_bincode`.
enum FerricError ferric_engine_deserialize_json(const uint8_t *data,
                                                uintptr_t len,
                                                struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Serialize engine state to CBOR.
//
// See `ferric_engine_serialize_bincode` for memory allocation details.
//
// # Safety
//
// Same safety requirements as `ferric_engine_serialize_bincode`.
enum FerricError ferric_engine_serialize_cbor(const struct FerricEngine *engine,
                                              FerricAllocFn alloc_fn,
                                              void *alloc_context,
                                              uint8_t **out_data,
                                              uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from CBOR bytes.
//
// # Safety
//
// Same safety requirements as `ferric_engine_deserialize_bincode`.
enum FerricError ferric_engine_deserialize_cbor(const uint8_t *data,
                                                uintptr_t len,
                                                struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Serialize engine state to `MessagePack`.
//
// See `ferric_engine_serialize_bincode` for memory allocation details.
//
// # Safety
//
// Same safety requirements as `ferric_engine_serialize_bincode`.
enum FerricError ferric_engine_serialize_msgpack(const struct FerricEngine *engine,
                                                 FerricAllocFn alloc_fn,
                                                 void *alloc_context,
                                                 uint8_t **out_data,
                                                 uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from `MessagePack` bytes.
//
// # Safety
//
// Same safety requirements as `ferric_engine_deserialize_bincode`.
enum FerricError ferric_engine_deserialize_msgpack(const uint8_t *data,
                                                   uintptr_t len,
                                                   struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Serialize engine state to Postcard.
//
// See `ferric_engine_serialize_bincode` for memory allocation details.
//
// # Safety
//
// Same safety requirements as `ferric_engine_serialize_bincode`.
enum FerricError ferric_engine_serialize_postcard(const struct FerricEngine *engine,
                                                  FerricAllocFn alloc_fn,
                                                  void *alloc_context,
                                                  uint8_t **out_data,
                                                  uintptr_t *out_len);
#endif

#if defined(FERRIC_SERDE)
// Deserialize an engine from Postcard bytes.
//
// # Safety
//
// Same safety requirements as `ferric_engine_deserialize_bincode`.
enum FerricError ferric_engine_deserialize_postcard(const uint8_t *data,
                                                    uintptr_t len,
                                                    struct FerricEngine **out_engine);
#endif

#if defined(FERRIC_SERDE)
// Free a byte buffer that was allocated by a serialize function when
// `alloc_fn` was null.
//
// Null pointers and zero lengths are safely ignored.
//
// # Safety
//
// - `data` must be a pointer returned by a serialize function (with
//   null `alloc_fn`), or null.
// - `len` must be the length reported by the corresponding serialize call.
// - The buffer must not have been previously freed.
void ferric_bytes_free(uint8_t *data, uintptr_t len);
#endif

// Retrieve the last global error message as a C string pointer.
//
// Returns a pointer to a NUL-terminated UTF-8 string, or null if no error
// is stored. The returned pointer is valid only until the next FFI call
// that may modify the global error channel.
//
// # Safety
//
// The returned pointer must not be freed by the caller and must not be
// used after any subsequent FFI call that may modify the error channel.
const char * FERRIC_NULL_TERMINATED ferric_last_error_global(void);

// Clear the global error channel.
void ferric_clear_error_global(void);

// Copy the last global error message into a caller-provided buffer.
//
// ## Contract
//
// | Condition | Return | `*out_len` |
// |-----------|--------|------------|
// | No error stored | `NotFound` | 0 |
// | `buf` is null AND `buf_len` is 0 (size query) | `Ok` | required size (incl. NUL) |
// | `buf` non-null, `buf_len` >= needed | `Ok` | bytes written (incl. NUL) |
// | `buf` non-null, `buf_len` < needed | `BufferTooSmall` | full needed size (incl. NUL) |
// | `buf_len` is 0 with non-null `buf` | `BufferTooSmall` | full needed size (incl. NUL) |
// | `out_len` is null | `InvalidArgument` | (not written) |
//
// When truncation occurs (`BufferTooSmall`), the buffer receives `buf_len - 1`
// bytes of the message followed by a NUL terminator. If `buf_len` is 0,
// nothing is written.
//
// # Safety
//
// - `buf` must point to `buf_len` writable bytes, or be null for size query.
// - `out_len` must be a valid pointer (non-null).
enum FerricError ferric_last_error_global_copy(char *buf FERRIC_SIZED_BY(buf_len), uintptr_t buf_len, uintptr_t *out_len);

// Create an integer `FerricValue`.
struct FerricValue ferric_value_integer(int64_t value);

// Create a float `FerricValue`.
struct FerricValue ferric_value_float(double value);

// Create a symbol `FerricValue` with a heap-copied string.
//
// Returns a void value if `name` is null. The caller owns the
// `string_ptr` and must free it with `ferric_value_free`.
//
// # Safety
//
// - `name` must be a valid NUL-terminated string, or null.
struct FerricValue ferric_value_symbol(const char * FERRIC_NULL_TERMINATED name);

// Create a string `FerricValue` with a heap-copied string.
//
// Returns a void value if `s` is null. The caller owns the
// `string_ptr` and must free it with `ferric_value_free`.
//
// # Safety
//
// - `s` must be a valid NUL-terminated string, or null.
struct FerricValue ferric_value_string(const char * FERRIC_NULL_TERMINATED s);

// Create a void `FerricValue` with all fields zeroed/null.
struct FerricValue ferric_value_void(void);

// Free a heap-allocated C string returned by the FFI.
//
// Null pointers are safely ignored.
//
// # Safety
//
// - `ptr` must be a pointer returned by an FFI function or null.
// - The pointer must not have been freed already.
void ferric_string_free(char * FERRIC_NULL_TERMINATED ptr);

// Free a `FerricValue` and its owned resources.
//
// Recursively frees owned strings and multifield arrays.
// Null pointers are safely ignored.
//
// # Safety
//
// - `value` must point to a valid `FerricValue` or be null.
// - Any owned resources (`string_ptr`, `multifield_ptr`) must not have been freed already.
void ferric_value_free(struct FerricValue *value);

// Free an array of `FerricValue`s and all their owned resources.
//
// Frees each element's owned resources, then frees the array allocation.
// Null pointers are safely ignored.
//
// # Safety
//
// - `arr` must point to a contiguous array of `len` `FerricValue`s, or be null.
// - The array must have been allocated by the FFI.
void ferric_value_array_free(struct FerricValue *arr FERRIC_COUNTED_BY(len), uintptr_t len);

#endif  /* FERRIC_H */
