#!/usr/bin/env bash
#
# Compose a PR assessment comment from the compat comparison artifact,
# then find-or-update the comment on the PR.
#
# Usage:
#   scripts/compose-pr-comment.sh \
#     --pr NUMBER \
#     --compat-report FILE \
#     --compat-status STATUS
#
# STATUS values match GitHub Actions job result: success, failure, cancelled, skipped
#
# Requires: gh CLI authenticated via GH_TOKEN or GITHUB_TOKEN

set -euo pipefail

MARKER="<!-- pr-assessment-report -->"
PR=""
COMPAT_REPORT=""
COMPAT_STATUS=""

usage() {
    cat <<'EOF'
Usage: scripts/compose-pr-comment.sh [OPTIONS]

Compose and post a PR assessment comment.

Options:
  --pr NUMBER             PR number (required)
  --compat-report FILE    Path to compat diff report markdown
  --compat-status STATUS  Compat job result (success|failure|cancelled|skipped)
  -h, --help              Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pr)           PR="$2"; shift 2 ;;
        --compat-report) COMPAT_REPORT="$2"; shift 2 ;;
        --compat-status) COMPAT_STATUS="$2"; shift 2 ;;
        -h|--help)      usage; exit 0 ;;
        *)              echo "error: unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
done

if [[ -z "$PR" ]]; then
    echo "error: --pr is required" >&2
    exit 1
fi

# Default empty status variables
[[ -z "$COMPAT_STATUS" ]] && COMPAT_STATUS="unknown"

# ── Status emoji ────────────────────────────────────────────────────────────

status_emoji() {
    local status="$1"
    case "$status" in
        success)   echo "pass" ;;
        failure)   echo "fail" ;;
        cancelled) echo "cancelled" ;;
        skipped)   echo "skipped" ;;
        *)         echo "unknown" ;;
    esac
}

# ── Compose body ────────────────────────────────────────────────────────────

# GitHub rejects comments over 65,536 characters. Measure bytes (the report has
# multi-byte characters) and keep well under the limit; the footer follows.
MAX_REPORT_BYTES="${PR_COMMENT_MAX_REPORT_BYTES:-60000}"
BODY_FILE="$(mktemp)"
REPORT_FILE="$(mktemp)"
trap 'rm -f "$BODY_FILE" "$REPORT_FILE"' EXIT

{
    printf '%s\n' "$MARKER" "# PR Assessment Report" ""
    if [[ -n "$COMPAT_REPORT" ]] && [[ -f "$COMPAT_REPORT" ]]; then
        cat "$COMPAT_REPORT"
    else
        printf '%s\n' "## CLIPS Compatibility Report" ""
        printf '%s\n' "> Compatibility assessment did not complete (status: ${COMPAT_STATUS:-unknown})."
        printf '%s\n' "> Check the [workflow run](../actions) for details."
    fi
} > "$REPORT_FILE"

if (( $(wc -c < "$REPORT_FILE") > MAX_REPORT_BYTES )); then
    # Cut at a line boundary, leaving room for the notice, and close a cut
    # <details> element. The marker and the corpus headline come first.
    LC_ALL=C awk -v limit="$((MAX_REPORT_BYTES - 1024))" '
        {
            size = length($0) + 1
            if (total + size > limit) exit
            total += size
            print
            open += gsub(/<details[ >]/, "&") - gsub(/<\/details>/, "&")
        }
        END { if (open > 0) print "\n</details>" }
    ' "$REPORT_FILE" > "$BODY_FILE"
    if [[ -n "${GITHUB_RUN_ID:-}" ]]; then
        RUN_LINK="[workflow run](${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID})"
    else
        RUN_LINK="PR Assessment workflow run"
    fi
    printf '\n> **Report truncated** to fit the GitHub comment size limit. The full report is `compat-diff-report.md` in the `compat-diff-report` artifact of this %s.\n' \
        "$RUN_LINK" >> "$BODY_FILE"
else
    cat "$REPORT_FILE" > "$BODY_FILE"
fi

# Footer
COMPAT_EMOJI="$(status_emoji "${COMPAT_STATUS:-unknown}")"
printf '\n%s\n%s\n' "---" "*Generated by PR Assessment | compat: ${COMPAT_EMOJI}*" >> "$BODY_FILE"

# ── Find existing comment ──────────────────────────────────────────────────

REPO="${GITHUB_REPOSITORY:-}"
if [[ -z "$REPO" ]]; then
    # Try to infer from gh
    REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
fi

if [[ -z "$REPO" ]]; then
    echo "error: cannot determine repository (set GITHUB_REPOSITORY)" >&2
    exit 1
fi

echo "==> Looking for existing assessment comment on PR #${PR}..."

COMMENT_ID=""
COMMENT_ID="$(gh api "repos/${REPO}/issues/${PR}/comments" \
    --paginate \
    --jq ".[] | select(.body | startswith(\"${MARKER}\")) | .id" \
    2>/dev/null | head -1 || true)"

# ── Post or update ──────────────────────────────────────────────────────────

if [[ -n "$COMMENT_ID" ]]; then
    echo "==> Updating existing comment ${COMMENT_ID}..."
    gh api "repos/${REPO}/issues/comments/${COMMENT_ID}" \
        -X PATCH \
        -F body=@"${BODY_FILE}" \
        --silent
else
    echo "==> Creating new comment..."
    gh pr comment "${PR}" --body-file "${BODY_FILE}"
fi

echo "==> Done."
