#!/usr/bin/env bash
#
# Compose a combined PR assessment comment from compat and perf artifacts,
# then find-or-update the comment on the PR.
#
# Usage:
#   scripts/compose-pr-comment.sh \
#     --pr NUMBER \
#     --compat-report FILE \
#     --perf-report FILE \
#     --compat-status STATUS \
#     --perf-status STATUS
#
# STATUS values match GitHub Actions job result: success, failure, cancelled, skipped
#
# Requires: gh CLI authenticated via GH_TOKEN or GITHUB_TOKEN

set -euo pipefail

MARKER="<!-- pr-assessment-report -->"
PR=""
COMPAT_REPORT=""
PERF_REPORT=""
COMPAT_STATUS=""
PERF_STATUS=""

usage() {
    cat <<'EOF'
Usage: scripts/compose-pr-comment.sh [OPTIONS]

Compose and post a combined PR assessment comment.

Options:
  --pr NUMBER             PR number (required)
  --compat-report FILE    Path to compat diff report markdown
  --perf-report FILE      Path to perf diff report markdown
  --compat-status STATUS  Compat job result (success|failure|cancelled|skipped)
  --perf-status STATUS    Perf job result (success|failure|cancelled|skipped)
  -h, --help              Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pr)           PR="$2"; shift 2 ;;
        --compat-report) COMPAT_REPORT="$2"; shift 2 ;;
        --perf-report)  PERF_REPORT="$2"; shift 2 ;;
        --compat-status) COMPAT_STATUS="$2"; shift 2 ;;
        --perf-status)  PERF_STATUS="$2"; shift 2 ;;
        -h|--help)      usage; exit 0 ;;
        *)              echo "error: unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
done

if [[ -z "$PR" ]]; then
    echo "error: --pr is required" >&2
    exit 1
fi

# Default empty status variables
[[ -z "$COMPAT_STATUS" ]] && COMPAT_STATUS="unknown"
[[ -z "$PERF_STATUS" ]] && PERF_STATUS="unknown"

# ── Status emoji ────────────────────────────────────────────────────────────

status_emoji() {
    local status="$1"
    case "$status" in
        success)   echo "pass" ;;
        failure)   echo "fail" ;;
        cancelled) echo "cancelled" ;;
        skipped)   echo "skipped" ;;
        *)         echo "unknown" ;;
    esac
}

# ── Compose body ────────────────────────────────────────────────────────────

BODY="$MARKER"
BODY+=$'\n'"# PR Assessment Report"$'\n'

# Compatibility section
if [[ -n "$COMPAT_REPORT" ]] && [[ -f "$COMPAT_REPORT" ]]; then
    BODY+=$'\n'"$(cat "$COMPAT_REPORT")"$'\n'
else
    BODY+=$'\n'"## CLIPS Compatibility Report"$'\n'
    BODY+=$'\n'"> Compatibility assessment did not complete (status: ${COMPAT_STATUS:-unknown})."$'\n'
    BODY+="> Check the [workflow run](../actions) for details."$'\n'
fi

BODY+=$'\n'"---"$'\n'

# Performance section
if [[ -n "$PERF_REPORT" ]] && [[ -f "$PERF_REPORT" ]]; then
    BODY+=$'\n'"$(cat "$PERF_REPORT")"$'\n'
else
    BODY+=$'\n'"## Performance Report"$'\n'
    BODY+=$'\n'"> Performance assessment did not complete (status: ${PERF_STATUS:-unknown})."$'\n'
    BODY+="> Check the [workflow run](../actions) for details."$'\n'
fi

# Footer
COMPAT_EMOJI="$(status_emoji "${COMPAT_STATUS:-unknown}")"
PERF_EMOJI="$(status_emoji "${PERF_STATUS:-unknown}")"
BODY+=$'\n'"---"$'\n'
BODY+="*Generated by PR Assessment | compat: ${COMPAT_EMOJI} | perf: ${PERF_EMOJI}*"$'\n'

# ── Find existing comment ──────────────────────────────────────────────────

REPO="${GITHUB_REPOSITORY:-}"
if [[ -z "$REPO" ]]; then
    # Try to infer from gh
    REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
fi

if [[ -z "$REPO" ]]; then
    echo "error: cannot determine repository (set GITHUB_REPOSITORY)" >&2
    exit 1
fi

echo "==> Looking for existing assessment comment on PR #${PR}..."

COMMENT_ID=""
COMMENT_ID="$(gh api "repos/${REPO}/issues/${PR}/comments" \
    --paginate \
    --jq ".[] | select(.body | startswith(\"${MARKER}\")) | .id" \
    2>/dev/null | head -1 || true)"

# ── Post or update ──────────────────────────────────────────────────────────

if [[ -n "$COMMENT_ID" ]]; then
    echo "==> Updating existing comment ${COMMENT_ID}..."
    gh api "repos/${REPO}/issues/comments/${COMMENT_ID}" \
        -X PATCH \
        -f body="${BODY}" \
        --silent
else
    echo "==> Creating new comment..."
    gh pr comment "${PR}" --body "${BODY}"
fi

echo "==> Done."
