/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Conflict resolution strategy for the Rete agenda. */
export const enum Strategy {
  /** Depth-first (CLIPS default). */
  Depth = 0,
  /** Breadth-first. */
  Breadth = 1,
  /** LEX (lexicographic recency). */
  Lex = 2,
  /** MEA (means-ends analysis). */
  Mea = 3
}
/** String encoding constraint for symbols and strings. */
export const enum Encoding {
  /** ASCII-only. */
  Ascii = 0,
  /** UTF-8 (default). */
  Utf8 = 1,
  /** ASCII symbols, UTF-8 strings. */
  AsciiSymbolsUtf8Strings = 2
}
/** Serialization format for engine snapshots. */
export const enum Format {
  /** Compact binary (bincode). Fast and small. */
  Bincode = 0,
  /** JSON (human-readable). */
  Json = 1,
  /** CBOR. */
  Cbor = 2,
  /** `MessagePack`. */
  MessagePack = 3,
  /** Postcard. */
  Postcard = 4
}
/** Options for constructing an [`Engine`]. */
export interface EngineOptions {
  /** Conflict resolution strategy (default: Depth). */
  strategy?: Strategy
  /** String encoding mode (default: Utf8). */
  encoding?: Encoding
  /** Maximum call depth for user-defined functions (default: engine default). */
  maxCallDepth?: number
}
/** Fact type discriminator. */
export const enum FactType {
  /** An ordered (positional) fact. */
  Ordered = 0,
  /** A template (named-slot) fact. */
  Template = 1
}
/** Why the engine stopped executing. */
export const enum HaltReason {
  /** The agenda was empty. */
  AgendaEmpty = 0,
  /** The run limit was reached. */
  LimitReached = 1,
  /** A halt was explicitly requested. */
  HaltRequested = 2
}
/** Result of a `run()` call. */
export interface RunResult {
  /** Number of rules fired during this run. */
  rulesFired: number
  /** Why execution stopped. */
  haltReason: HaltReason
}
/** Information about a single rule that fired. */
export interface FiredRule {
  /** The name of the rule that fired. */
  ruleName: string
}
/** Summary information about a registered rule. */
export interface RuleInfo {
  /** Rule name. */
  name: string
  /** Rule salience (priority). */
  salience: number
}
/**
 * The Ferric rules engine — Node.js binding.
 *
 * This wraps a `ferric_runtime::Engine` and exposes it to JavaScript via
 * napi-rs.  Because napi-rs objects cannot cross V8 thread boundaries, no
 * thread-local registry is needed — the engine is stored directly in the
 * struct.
 */
export declare class Engine {
  /** Create a new, empty engine. */
  constructor(options?: EngineOptions | undefined | null)
  /**
   * Create an engine from CLIPS source, loading and resetting in one step.
   *
   * Equivalent to constructing an engine, calling `load(source)`, then
   * `reset()`.
   */
  static fromSource(source: string, options?: EngineOptions | undefined | null): Engine
  /** Load CLIPS source into the engine. */
  load(source: string): void
  /** Load CLIPS source from a file at the given path. */
  loadFile(path: string): void
  /**
   * Assert one or more facts from CLIPS syntax (e.g. `"(color red)"`).
   *
   * Returns an array of fact IDs (as `number`) for all asserted facts.
   */
  assertString(source: string): Array<number>
  /**
   * Assert an ordered fact with the given relation name and field values.
   *
   * Field values may be `null`, `boolean`, `number`, `bigint`, `string`,
   * `FerricSymbol`, or `Array`.
   */
  assertFact(relation: string, ...fields: unknown[]): number
  /**
   * Assert a template fact by template name and slot values.
   *
   * `slots` is a plain JS object whose keys are slot names and values are
   * CLIPS values (`null`, `boolean`, `number`, `bigint`, `string`,
   * `FerricSymbol`, or `Array`).
   */
  assertTemplate(templateName: string, slots: object): number
  /** Retract a fact by its ID. */
  retract(factId: number): void
  /** Get a fact by its ID, or `null` if it does not exist. */
  getFact(factId: number): unknown
  /** Return all user-visible facts as a JS array of fact objects. */
  facts(): object
  /** Find facts by relation name. Returns a JS array of fact objects. */
  findFacts(relation: string): object
  /** Get the value of a template fact slot by name. */
  getFactSlot(factId: number, slotName: string): unknown
  /**
   * Run the engine, optionally limiting the number of rule firings.
   *
   * Returns a `RunResult` describing how many rules fired and why
   * execution stopped.
   */
  run(limit?: number | undefined | null): RunResult
  /** Fire a single rule activation. Returns a `FiredRule` or `null`. */
  step(): FiredRule | null
  /** Request the engine to halt after the current rule completes. */
  halt(): void
  /** Reset the engine: clear facts and re-assert deffacts. */
  reset(): void
  /** Clear the engine: remove all rules, facts, templates, globals, etc. */
  clear(): void
  /** Number of user-visible facts in working memory. */
  get factCount(): number
  /** Whether the engine is currently halted. */
  get isHalted(): boolean
  /** Number of pending activations on the agenda. */
  get agendaSize(): number
  /** Name of the current module. */
  get currentModule(): string
  /** Top of the focus stack, or `null` if the focus stack is empty. */
  get focus(): string | null
  /** Full focus stack as an array of module names (bottom to top). */
  get focusStack(): Array<string>
  /** Non-fatal action diagnostics from the most recent `run()`/`step()`. */
  get diagnostics(): Array<string>
  /** List all registered rules with their names and salience values. */
  rules(): Array<RuleInfo>
  /** List the names of all registered templates. */
  templates(): Array<string>
  /** List the names of all registered modules. */
  modules(): Array<string>
  /** Get the value of a global variable by name, or `null` if not set. */
  getGlobal(name: string): unknown
  /** Set focus to a single module, replacing the previous focus stack. */
  setFocus(moduleName: string): void
  /** Push a module onto the focus stack. */
  pushFocus(moduleName: string): void
  /**
   * Get captured output for a channel (e.g. `"stdout"`).
   *
   * Returns `null` if the channel has no captured output.
   */
  getOutput(channel: string): string | null
  /** Clear captured output for a channel. */
  clearOutput(channel: string): void
  /** Push a line of input for `read`/`readline` to consume. */
  pushInput(line: string): void
  /** Clear accumulated action diagnostics. */
  clearDiagnostics(): void
  /** Serialize the engine state to a Node.js `Buffer`. */
  serialize(format?: Format | undefined | null): Buffer
  /** Create an engine by deserializing from a Node.js `Buffer`. */
  static fromSnapshot(data: Buffer, format?: Format | undefined | null): Engine
  /** Create an engine by deserializing from a file. */
  static fromSnapshotFile(path: string, format?: Format | undefined | null): Engine
  /** Save a serialized engine snapshot to a file. */
  saveSnapshot(path: string, format?: Format | undefined | null): void
  /**
   * Explicitly close and destroy this engine.
   *
   * After calling `close()`, any further method calls will throw an error.
   * This is idempotent — calling it multiple times is safe.
   */
  close(): void
}
/**
 * A CLIPS symbol value — distinct from a plain string.
 *
 * In CLIPS, symbols and strings are different types. A JavaScript `string`
 * maps to a CLIPS `String` (quoted). To pass a CLIPS Symbol, wrap the name
 * in a `FerricSymbol`.
 */
export declare class FerricSymbol {
  /** Create a new CLIPS symbol with the given name. */
  constructor(value: string)
  /** The symbol name. */
  get value(): string
  /** Return the symbol name as a string. */
  toString(): string
  /** Return the symbol name (for JS `valueOf` protocol). */
  valueOf(): string
}
